DROP TABLE "Progetto"."business-openhours";
DROP TABLE "Progetto"."business-categories";
DROP TABLE "Progetto"."business-neighborhoods";
DROP TABLE "Progetto"."user-profiles";
DROP TABLE "Progetto"."user-votes";
DROP TABLE "Progetto"."user-compliments";
DROP TABLE "Progetto"."review-votes";
DROP TABLE "Progetto"."reviews";
DROP TABLE "Progetto"."user-friends";
DROP SCHEMA "Progetto"